version: "3.3"
services:

  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - flask-project-structure

  flask:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app:create_app()"
    environment:
      FLASK_ENV: PRODUCTION
    volumes:
      - ../:/var/wwww
    networks:
      - flask-project-structure
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - flask-project-structure
    depends_on:
      - flask

networks:
  flask-project-structure:
